import { demoScenarios } from "@/lib/demo";
import { AppShell, PageHeader } from "@/app/components/workflow-ui";
import { DemoClient } from "./demo-client";

export default function DemoPage() {
  const scenarios = demoScenarios.map((scenario) => ({
    scenarioId: scenario.scenarioId,
    name: scenario.name,
    description: scenario.description,
    disclaimerText: scenario.disclaimerText,
    defaultEditableTranscript: scenario.defaultEditableTranscript,
  }));

  return (
    <AppShell>
      <PageHeader eyebrow="Phase 4 demo" title="Backend Hygiene Analysis Demo" description="Inspect deterministic extraction, validation, scoring, and recommendations generated by backend APIs before any approval or writeback UI is introduced." />
      <DemoClient scenarios={scenarios} />
    </AppShell>
  );
}
